"""DiskHTML 桌面界面的中文文案。"""

WINDOW_TITLE = "DiskHTML - HTML 快照生成器"
READY = "就绪"
TAB_SNAPSHOT = "生成目录快照"
TAB_COMPARE = "生成比对报告"
TAB_SQLITE = "从 SQLite 生成"

SNAPSHOT_HEADING = "生成目录快照"
SNAPSHOT_DESCRIPTION = "生成可离线打开的 HTML 文件快照。"
COMPARE_HEADING = "生成比对报告"
COMPARE_DESCRIPTION = "生成一个可离线打开的 HTML，比对已有快照与当前目录。"
SQLITE_HEADING = "从 SQLite 生成"
SQLITE_DESCRIPTION = "不重新扫描原目录，直接生成新版本 HTML。"

SOURCE_DIRECTORY = "源目录"
BASELINE_SNAPSHOT = "基准快照"
CHECK_DIRECTORY = "待检查目录"
OUTPUT_HTML = "输出 HTML"
OUTPUT_REPORT = "输出报告"
SQLITE_INDEX = "SQLite 快照索引"
SELECT_DIRECTORY = "选择目录"
SELECT_SNAPSHOT = "选择快照"
SELECT_SQLITE = "选择 SQLite"
CHANGE_LOCATION = "更改位置"
FOLLOW_LINKS = "跟随软链接和 Windows 重解析点"
CREATE_SNAPSHOT = "生成快照 HTML"
CREATE_COMPARE = "生成比对 HTML"
CREATE_SQLITE = "从 SQLite 生成 HTML"
SNAPSHOT_ROOT = "快照根目录"
SNAPSHOT_DIRECTORY = "快照内目录"
SELECT_ARCHIVED_DIRECTORY = "选择快照内目录"

SNAPSHOT_SOURCE_HELP = "需要保存为快照的文件夹。"
SNAPSHOT_OUTPUT_HELP = "将同时生成同名 SQLite 索引。"
ARCHIVE_HELP = "之前生成的 DiskHTML HTML 快照。"
CHECK_DIRECTORY_HELP = "当前需要与快照比较的实际文件夹。"
COMPARE_OUTPUT_HELP = "比对结果将保存为可离线打开的 HTML。"
SQLITE_HELP = "生成快照时同名保留的 .sqlite3 文件。"
SQLITE_OUTPUT_HELP = "新的 HTML 输出文件必须不存在。"

PAUSE = "暂停"
RESUME = "继续"
CANCEL = "取消"
OPEN_HTML = "打开 HTML"
OPEN_FOLDER = "打开所在文件夹"
SUCCESS = "生成成功"
TASK_FAILED = "任务失败"
CURRENT_STAGE = "当前阶段"
CURRENT_PATH = "正在处理的路径"
FILES_SCANNED = "已扫描文件数"
HASH_PROGRESS = "Hash 进度"
WAITING_SCAN = "等待扫描"
WAITING_FILE = "等待下一个文件"
CREATE_SNAPSHOT_STAGE = "正在生成 HTML 快照。"
CREATE_COMPARE_STAGE = "正在扫描待检查目录并生成比对 HTML。"
CREATE_SQLITE_STAGE = "正在从 SQLite 生成 HTML。"
SCANNING_HASH_STAGE = "正在扫描并计算 Hash"
REQUESTED_ACTION = "已请求"
HTML_CREATED = "HTML 已生成"
COMPARE_CREATED = "比对 HTML 已生成"
DIRECTORY_REQUIRED = "请选择存在的目录。"
ARCHIVE_REQUIRED = "请选择存在的 DiskHTML HTML 快照。"
SQLITE_REQUIRED = "请选择存在的 SQLite 快照索引。"
OUTPUT_HTML_REQUIRED = "输出文件必须是新的 .html 文件。"
OUTPUT_EXISTS = "输出 HTML 已存在，请更换一个名称。"
OUTPUT_NOT_WRITABLE = "输出目录不存在或不可写。"
ARCHIVE_INVALID = "快照格式无效"
